version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "16:00"
  open-pull-requests-limit: 0
  target-branch: develop
  reviewers:
  - patrykjadamczyk
  assignees:
  - patrykjadamczyk
  allow:
  - dependency-type: direct
  - dependency-type: indirect
