name: Tests

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 9
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Installing PWBS
      run: |
        pip install -e .[dev,test,setup,docs]
    - name: Run PyTest Tests
      run: |
        pytest
    - name: Run PWBS Tests
      run: |
        pwbs --run-tests
    - name: Lint with pylint
      continue-on-error: true
      run: |
        pylint **/*.py
